name: inkwisp threads

on:
  workflow_dispatch:  # Manual run button
  
  schedule:
  - cron: '15 1 * * *'   # 06:45 AM IST   
  - cron: '0 15 * * *'   # 08:30 PM IST  
  


jobs:
  post-to-threads:
    runs-on: ubuntu-latest

    env:
      THREADS_USER_ID_1: ${{ secrets.THREADS_USER_ID_1 }}
      THREADS_ACCESS_TOKEN_1: ${{ secrets.THREADS_ACCESS_TOKEN_1 }}
      DROPBOX_APP_KEY_1: ${{ secrets.DROPBOX_APP_KEY_1 }}
      DROPBOX_APP_SECRET_1: ${{ secrets.DROPBOX_APP_SECRET_1 }}
      DROPBOX_REFRESH_TOKEN_1: ${{ secrets.DROPBOX_REFRESH_TOKEN_1 }}

      THREADS_USER_ID_2: ${{ secrets.THREADS_USER_ID_2 }}
      THREADS_ACCESS_TOKEN_2: ${{ secrets.THREADS_ACCESS_TOKEN_2 }}
      DROPBOX_APP_KEY_2: ${{ secrets.DROPBOX_APP_KEY_2 }}
      DROPBOX_APP_SECRET_2: ${{ secrets.DROPBOX_APP_SECRET_2 }}
      DROPBOX_REFRESH_TOKEN_2: ${{ secrets.DROPBOX_REFRESH_TOKEN_2 }}

      THREADS_USER_ID_3: ${{ secrets.THREADS_USER_ID_3 }}
      THREADS_ACCESS_TOKEN_3: ${{ secrets.THREADS_ACCESS_TOKEN_3 }}
      DROPBOX_APP_KEY_3: ${{ secrets.DROPBOX_APP_KEY_3 }}
      DROPBOX_APP_SECRET_3: ${{ secrets.DROPBOX_APP_SECRET_3 }}
      DROPBOX_REFRESH_TOKEN_3: ${{ secrets.DROPBOX_REFRESH_TOKEN_3 }}

      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dropbox python-telegram-bot==13.15 requests pytz

      - name: Run Dropbox to Threads script
        run: python "ink_wisp.py"
